[MOB-18293] - Handling Notification Actions
adobe/aepsdk-messaging-ios pull request #174
Opened 2023-04-11 20:49 UTC by PravinPK

### Definition
Notification Action is defined as an action that the Messaging Extension takes in response to interacting with the notification.
Typically these actions can be to open a web URL or a deeplink associated with that application.

### How notification action is set
While designing a push notification campaign. Notification action is set by editing the click behavior field.
In iOS deeplink/ weburl action links are sent to the device through the push notification payload. They are available in a custom field "adb_uri".

![Screenshot 2023-04-11 at 11 52 56 AM](https://user-images.githubusercontent.com/8909148/231261124-49e8d8f8-9b8e-4b25-a28c-aa568864fcdf.png). 

### Notification body click action 
Notification body click action determines the action taken when clicking on the body of the notification. This will typically open the application and hence requires the customers to call  Messaging API handleNotificationResponse with  applicationOpened : true
customActionId : nil
`Messaging.handleNotificationResponse(response, applicationOpened: true, customActionId: nil)`

###  Notification custom button click action
Notification custom button click action determines the action taken when the user clicks either of the action buttons in a notification. On this action we require the customers to call Messaging API handleNotificationResponse with
applicationOpened : true/false (depending upon if the action was set to bring the application to foreground)
customActionId : response.actionIdentifier

`Messaging.handleNotificationResponse(response, applicationOpened: false/true, customActionId: response.actionIdentifier)`

![image](https://user-images.githubusercontent.com/8909148/231264345-a4a9d29d-45b3-4903-a949-dd515b236dc1.png)

### Why cant we handle notification custom button click action
With the [examples](https://github.com/adobe/aepsdk-messaging-ios/compare/main...PravinPK:aepsdk-messaging-ios:dev-v1.1.1?expand=1#diff-7b5f15992292d4c8a9c5241e39c2f11afced0fc54a089fb8d0b3492105e08c4eR143-R180) in this PR. The notification custom actions along with its category is pre-created by the application and registered at launch time. Therefore AJO doesn't control the creation of action buttons from its authoring UI. The authoring UI should only ask for the categoryID of the already registered category that can be invoked. 

Since AJO doesn't have the power to define the actions of a custom notification button. So Messaging SDK would not be able to handle the custom notification action links. This has to be handled by the application as shown [here](https://github.com/adobe/aepsdk-messaging-ios/compare/main...PravinPK:aepsdk-messaging-ios:dev-v1.1.1?expand=1#diff-7b5f15992292d4c8a9c5241e39c2f11afced0fc54a089fb8d0b3492105e08c4eR184-R196).

### A Complex Scenario
Assume a user designs a notification such that
1. Clicking on the body should open a deeplink
2. Clicking on the not

2023-04-11 22:37 UTC, sbenedicadb requested changes

2023-04-11 22:37 UTC, sbenedicadb commented on AEPMessaging/Sources/Messaging+PublicAPI.swift
> +                if let actionUrl = notificationRequest.content.userInfo [MessagingConstants.PushNotification.UserInfoKey.ACTION_URL] as? String {
nit: no space between dictionary and subscript `userInfo[Messaging...`

2023-04-11 22:37 UTC, sbenedicadb commented on AEPMessaging/Sources/Messaging+PublicAPI.swift
> +                // (TODO: Decide if we should also accept UNNotificationDefaultActionIdentifier as customActionId to process sending the clickthrough url through eventData)
do we need to chat about this?

2023-04-11 22:37 UTC, sbenedicadb commented on AEPMessaging/Sources/Messaging.swift
> +            //  Handle push click through action if the event data contains the web/deeplink
click-through

2023-04-11 22:37 UTC, sbenedicadb commented on AEPMessaging/Sources/Messaging.swift
> +            }
should we swap the order of these? did we test to make sure the tracking call still goes through even after navigating away potentially to another app?

2023-04-11 22:37 UTC, sbenedicadb commented on AEPMessaging/Sources/Messaging.swift
> +            if(configSharedState.keys.contains(MessagingConstants.SharedState.Configuration.EXPERIENCE_EVENT_DATASET)) {
nit: don't use params on `if` statements 😄

2023-04-11 22:37 UTC, sbenedicadb commented on AEPMessaging/Sources/Event+Messaging.swift
> +    var pushClickThroughLink: URL? {
maybe rename to `pushClickThroughUrl`?

2023-07-13 16:44 UTC, PravinPK commented
Closing this PR. Will put up another PR with a new API that can handle actions on notifications

2023-07-13 16:44 UTC, closed without merging