-4.x doc for review
adobe/aepsdk-messaging-ios pull request #191
Opened 2023-06-06 23:42 UTC by sbenedicadb

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-06 23:51 UTC, swarna04 requested changes

2023-06-06 23:51 UTC, swarna04 commented on iOS_4x_release.md
> +You may be wondering "what happened to versions 2 and 3 of AEPEdge?"  Our apologies for any confusion this may cause.  In order to achieve our goal of unifying major versions, some extensions, AEPEdg
Fix grammar and typos - `Hopefully our explanation above has shed light on this anomaly.`

2023-06-06 23:51 UTC, swarna04 commented on iOS_4x_release.md
> +The main goal is to simplify the Adobe SDK distibution.  Aliging all extesions on the same major version allows us to create predictability.  For example:
distibution -> distribution
extesions -> extensions

2023-06-06 23:51 UTC, swarna04 commented on iOS_4x_release.md
> +Apple has started doing an annual requirement to increase the minimum version of Xcode used when submitting to the App Store.  Each Xcode version only supports back to a specific minimum version of i
Loosly -> Loosely

2023-06-06 23:51 UTC, swarna04 commented on iOS_4x_release.md
> +  - Possible increase to minimum supported version of Swift.
👍

2023-06-06 23:51 UTC, swarna04 commented on iOS_4x_release.md
> +### Will I have to re-implement the SDK?
re-implement -> reimplement

2023-06-06 23:51 UTC, swarna04 commented on iOS_4x_release.md
> +Unlike our previous major version updates, this is not a major re-write.  You should expect all of your API calls in the previous major version of the SDK to continue working with the new version (wi
re-write -> rewrite

2023-06-06 23:51 UTC, swarna04 commented on iOS_4x_release.md
> +Google has been making regular requirements to [increase target API levels for Google Play apps](https://support.google.com/googleplay/android-developer/answer/11926878?hl=en#).  While this requireme
Let's remove extra backtick (`) at the end.

2023-06-06 23:57 UTC, swarna04 commented on iOS_4x_release.md
> +The main goal is to simplify the Adobe SDK distibution.  Aliging all extesions on the same major version allows us to create predictability.  For example:
Aliging -> Aligning

2023-06-07 15:11 UTC, sbenedicadb commented on iOS_4x_release.md
> +# Aligning major version releases for the Adobe iOS SDK
yeah, sounds good.  the original intent was for this to feel like a blog post, and hopefully some of the content would be reusable for our docs.  let's figure out which parts of this we want to keep (or modify) for docs.

i'll add the sections you mention for semver and support of older versions.

2023-06-07 18:33 UTC, calebk1 reviewed
A few more comments! I'll do a re-review once your changes have been pushed.

But one thing I noticed throughout is the usage of double spaces between sentences - we can just make those single spaced instead. Thanks!

2023-06-07 18:33 UTC, calebk1 commented on iOS_4x_release.md
> +Apple has started doing an annual requirement to increase the minimum version of Xcode used when submitting to the App Store.  Each Xcode version only supports back to a specific minimum version of i
"Loosely speaking, the Xcode version and the minimum..."

2023-06-07 18:33 UTC, calebk1 commented on iOS_4x_release.md
> +https://developer.apple.com/ios/submit/
Is there a reason we have the submit link here?

2023-06-07 18:33 UTC, calebk1 commented on iOS_4x_release.md
> +The main goal is to simplify the Adobe SDK distibution.  Aliging all extesions on the same major version allows us to create predictability.  For example:
"Aligning the extensions on the same major version..."

Also, a double space between "... to create predictability." and "For example:".

2023-06-07 18:33 UTC, calebk1 commented on iOS_4x_release.md
> +The main goal is to simplify the Adobe SDK distibution.  Aliging all extesions on the same major version allows us to create predictability.  For example:
Just to be even clearer, I'd go with "... the Adobe Mobile SDK distribution."

2023-06-07 18:33 UTC, calebk1 commented on iOS_4x_release.md
> +You may be wondering "what happened to versions 2 and 3 of AEPEdge?"  Our apologies for any confusion this may cause.  In order to achieve our goal of unifying major versions, some extensions, AEPEdg
"... on this anomaly."

2023-06-07 19:50 UTC, sbenedicadb commented on iOS_4x_release.md
> +While we don't have plans for another major rewrite any time soon, if a need for one comes up, we will be sure to let you know with plenty of lead time.
which part? the "don't have plans..." part?

2023-06-07 21:39 UTC, praschetan commented on iOS_4x_release.md
> +Apple has started doing an annual requirement to increase the minimum version of Xcode used when [submitting to the App Store](https://developer.apple.com/ios/submit/). Each Xcode version only suppor
Can we link to a source?

2023-06-07 21:39 UTC, praschetan commented on iOS_4x_release.md
> + - Increasing the minimum supported version of Xcode.
Combine these bullets: Increasing minimum supported versions of iOS and Xcode

2023-06-07 21:39 UTC, praschetan commented on iOS_4x_release.md
> +The main goal for this change is to simplify Adobe Mobile SDK distribution. Aligning the extensions on the same major version allows us to create predictability. For example:
Use Adobe Experience Platform Mobile SDKs for iOS - for consistency

2023-06-07 21:40 UTC, praschetan commented on iOS_4x_release.md
> + - All Adobe-owned mobile SDK extensions that share a major version are compatible with one another.
"Adobe-provided"

2023-06-07 21:40 UTC, praschetan commented on iOS_4x_release.md
> + - Each major version of an Adobe-owned mobile SDK extension has a designated minimum supported OS version.
"Adobe-provided"

2023-06-07 21:41 UTC, praschetan commented on iOS_4x_release.md
> +### Do I have to reimplement the SDK?
I think this is a good FAQ to have.

2023-06-07 21:42 UTC, praschetan commented on iOS_4x_release.md
> +For starters, having more frequent updates allows us to better take advantage of new frameworks and APIs introduced by Apple. This will help us achieve a more modern SDK.
"This will help us remain a modern SDK that remains consistent and in lock-step with changes in iOS"

2023-06-07 21:43 UTC, praschetan commented on iOS_4x_release.md
> +A more subtle benefit of regular major releases is that we can safely remove deprecated APIs from the SDK. Over time, our API footprint can become bloated as requirements change internally. Methods t
A more subtle -> A subtle

2023-06-07 21:51 UTC, calebk1 reviewed
Some more comments!

2023-06-07 21:51 UTC, calebk1 commented on iOS_4x_release.md
> + - Possible increase to minimum supported version of Swift.
It feels a little awkward to have the possible here. Let's change this to "If necessary, increasing the minimum supported version of Swift."

2023-06-07 21:51 UTC, calebk1 commented on iOS_4x_release.md
> +You may be wondering "what happened to versions 2 and 3 of AEPEdge?"
Minor nit, but if this a quote, it should be '... be wondering "What happened to...'

2023-06-07 21:51 UTC, calebk1 commented on iOS_4x_release.md
> +Outside of major version updates, all of our extensions will continue to follow semantic versioning ([semver](https://semver.org/)) for MINOR and PATCH releases on an as-needed basis. We recommend us
Any reason that minor and patch are in all caps?

2023-06-07 21:51 UTC, calebk1 commented on iOS_4x_release.md
> +As previously mentioned, the main goal for our annual major update is to maintain support alignment with Apple. For this reason, we will not be supporting any version of our Swift SDK extensions othe
"... with Apple's requirements."

2023-06-07 21:51 UTC, calebk1 reviewed
Some more comments!

2023-06-07 22:02 UTC, sbenedicadb commented on iOS_4x_release.md
> +### Why are we getting another major update already?
ya, we can nit about formatting when we decide what goes in the markdown.  good callout though.

2023-06-07 22:03 UTC, sbenedicadb commented on iOS_4x_release.md
> +Apple has started doing an annual requirement to increase the minimum version of Xcode used when [submitting to the App Store](https://developer.apple.com/ios/submit/). Each Xcode version only suppor
how about "Apple is enforcing an annual requirement..."?

2023-06-07 22:04 UTC, calebk1 commented on iOS_4x_release.md
> +Apple has started doing an annual requirement to increase the minimum version of Xcode used when [submitting to the App Store](https://developer.apple.com/ios/submit/). Each Xcode version only suppor
That reads well to me!

2023-06-07 22:05 UTC, sbenedicadb commented on iOS_4x_release.md
> +Apple has started doing an annual requirement to increase the minimum version of Xcode used when [submitting to the App Store](https://developer.apple.com/ios/submit/). Each Xcode version only suppor
nevermind, i'll go with yours 😛

2023-06-13 14:59 UTC, closed without merging