Inbound refactor
adobe/aepsdk-messaging-ios pull request #227
Opened 2023-10-26 22:59 UTC by sbenedicadb

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-31 21:00 UTC, swarna04 commented
Steve, thanks for all the work here. I've provided my feedback, some of which bears questions/items we might need to address in near future.

2023-10-31 21:01 UTC, swarna04 requested changes

2023-11-03 19:44 UTC, sbenedicadb commented on AEPMessaging/Tests/Resources/cachedProposition.json
> +                    "data": {
this is a v1 iam handle and it's in the expected format 👍

2023-11-03 19:56 UTC, sbenedicadb commented on AEPMessaging/Tests/Resources/feedProposition.json
> +                                    "schema": "https://ns.adobe.com/personalization/inbound/feed-item",
one of the many tests to be updated 😄

2023-11-03 19:57 UTC, sbenedicadb commented on AEPMessaging/Tests/Resources/inboundConsequenceDetail.json
> +    "schema": "https://ns.adobe.com/personalization/inbound/feed-item",
nope.  i'll remove it.

2023-11-03 20:24 UTC, sbenedicadb commented on AEPMessaging/Sources/MessagingPropositionItem.swift
> +    public let propositionData: [String: Any]?
will rename to `itemId` and `itemData` for brevity

2023-11-06 15:55 UTC, sbenedicadb commented on AEPMessaging/Sources/schemas/FeedItemSchemaData.swift
> +    static func getEmpty() -> FeedItemSchemaData {
testing only - added a comment as such

2023-11-06 15:56 UTC, sbenedicadb commented on AEPMessaging/Sources/ParsedPropositions.swift
> +                    //    i. default-content schema consequences are treated like in-app at a proposition level
yes - 100%.  

results from ongoing rules engine discussions will determine path forward for supporting that.

2023-11-06 16:01 UTC, sbenedicadb commented on AEPMessaging/Sources/Messaging.swift
> +                        uniqueId: UUID().uuidString, // propositionInfo.id,
waiting for XAS updates to be deployed.  leaving these in for now as they enable e2e testing.

2023-11-06 22:50 UTC, swarna04 commented on AEPMessaging/Sources/schemas/FeedItemSchemaData.swift
> +    static func getEmpty() -> FeedItemSchemaData {
nit: We should use conditional compilation for these #if DEBUG...#endif, just the way we are doing for some other methods needed for testing purposes only.

2023-11-06 22:51 UTC, swarna04 commented on AEPMessaging/Sources/schemas/InAppSchemaData.swift
> +extension InAppSchemaData {
👍

2023-11-06 23:10 UTC, swarna04 commented on AEPMessaging/Sources/MessagingPropositionItem.swift
> +        return try? JSONDecoder().decode(MessagingPropositionItem.self, from: detailsData)
This still needs to be addressed, we do not want to lose the original item Id (by replacing with schema consequence Id) as we shall need to echo it back during item level tracking.

2023-11-06 23:24 UTC, swarna04 approved these changes

2023-11-06 23:24 UTC, merged